### ISSUE TITLE
Strict ruleset validation

### ISSUE THREAD

**Issue by wilrodriguez** [ryan95f/yamlator#40]
First off, this is a super cool module. Very well documented and designed. I would like to see an option, however, to run strict validation of a ruleset, such that I could create a ruleset that would only allow a listed set of keys. As I understand it currently from the documentation, this doesn't seem to be possible.

Say that I have a data structure that looks like this:
```yaml
foo:
  bar: true
  baz: false
  qux: 11
```

I would expect that I could validate this structure with something like
```
ruleset Foo {
    bar bool required
    baz bool required
    qux int required
}

schema foo {
    foo Foo
}
```

And while that will validate successfully, if I was to add `quux: corge` into foo, then it would still validate successfully, even though `quux` is not a listed valid key name.

**Comment by ryan95f** [comment]
Hi @wilrodriguez, thank you for the feedback and suggestion. This is a great idea and I will look to implement this as an enhancement.

**Comment by wilrodriguez** [comment]
Thanks for taking a look at my issue so quickly! I was thinking that perhaps the smoothest way to implement it might be to add another ruleset type. You could call it something like strict_ruleset.

**Comment by ryan95f** [comment]
As part of merge request #41, I have implemented strict rulesets and schema blocks into the package as a toggle onto the existing types using the `strict` keyword. This change can be used by upgrading the package to `0.2.0`. 

Based on your example above, this is how strict mode can be used:

```text
strict ruleset Foo {
    bar bool required
    baz bool required
    qux int required
}

strict schema foo {
    foo Foo
}
```
Keys that are not defined in the rulesets or schema with the `strict` keyword will get a violation error listed in the output :)

**Comment by wilrodriguez** [comment]
This definitely fulfills my needs, thanks again!
