### ISSUE TITLE
Support for union data types

### ISSUE THREAD

**Issue by wilrodriguez** [ryan95f/yamlator#42]
First off, thanks again for quickly adopting my previous suggestion. Here's to hoping this is an even easier one. It would be handy if there could be a union type that allows multiple types to be tested. I have a few instances where either a string or an integer would be acceptable. But, this could be powerful in that it could allow for the simplification of regexes by allowing multiple simple regexes to be supplied for complex validations rather than trying to build one big scary one that can encompass all potential cases.

I was thinking that a potential implementation would look something like `union(<type1>, <type2>, ...)` so that you could have N number of types you test. Short of maybe allowing imports from another file, I can't think of too many other things that this schema grammar really needs.

**Comment by ryan95f** [comment]
File imports is a feature that I am looking to implement a some point. The introduction of a `union` is an interesting suggestion. I can see the power it would bring with multiple simple regexes. I would try to avoid unions being nested inside unions and raise an error if that situation occurs. 

I will take a look at your PR #43.

**Comment by wilrodriguez** [comment]
That's good thinking. I hadn't thought about that possibility. Though, I don't think that technically should be a problem, at least if I'm reading things correctly. Union should basically just validate successfully if _something_ passes.

**Comment by ryan95f** [comment]
As part of release `v0.3.0` I have added support for the union type. When defining a union it requires 2 or more sub types to be defined. For example:

```text
ruleset Foo {
    bar union(int, float)
}
```

At the moment it will only display a single violation if one or more of the types do not match. I originally wanted it to provide the sub violations for the field depending on which type it was to likely be. However complicated nesting of types makes it difficult to provide the correct set of violations. I will address this limitation in a later update.

**Comment by wilrodriguez** [comment]
Awesome! I'll close out my PR. That's pretty much exactly what I had in mind for it. I had been meaning to work on it for awhile but never got back to it. Thanks as always Ryan!
