### ISSUE TITLE
Dash in a rule name results in a parsing error

### ISSUE THREAD

**Issue by wilrodriguez** [ryan95f/yamlator#44]
Just discovered a fun little bug. Looks like dashes in rule names will generate a syntax error. Something like this:

```
Error on line 118, column 8.

    foo-bar Baz optional
       ^
```

You can use the following to replicate it:

```
ruleset Baz {
    qux str optional
}

schema {
    foo-bar Baz optional
}
```

**Comment by ryan95f** [comment]
Thanks for this. I will create a MR to solve this.

**Comment by wilrodriguez** [comment]
This one is just a regex issue. Just need a `-` at the end of the pattern in `grammar.lark` on lines 29-31.

```
required_rule: /[a-zA-Z0-9_-]+/ type "required" NEW_LINES
             | /[a-zA-Z0-9_-]+/ type NEW_LINES
optional_rule: /[a-zA-Z0-9_-]+/ type "optional" NEW_LINES
```

**Comment by wilrodriguez** [comment]
Notably... should probably also allow other symbol characters like `:%$@!^*()`. Could probably even update it to `\S` since YAML is pretty much flexible enough to allow most characters as a key... and you can pretty much bet _someone_ is going to need to have a key somewhere with some weird symbols. YAML supports setting any printable unicode character, especially if you quote your keys. So... it might rather naive to assume we can are going to be able to predict what someone will need for a key. Perhaps we can match a certain subset for plain values or match everything contained within quotes if they need something extra.

**Comment by ryan95f** [comment]
That is a very good point. I will expand my current PR #45 to include these suggestions.

**Comment by ryan95f** [comment]
As part of release `0.2.1`, rule names have been updated to allow for all unicode characters including dashes and spaces.

**Comment by wilrodriguez** [comment]
Awesome! Just confirmed your change fixes this issue. I'll open a separate enhancement issue for broadening the key definition. I made a few attempts at implementing it myself but LARK never liked my syntax and I'm not really sure why.
