### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by wilrodriguez** [ryan95f/yamlator#49]
Welp, things had been going great and I was just about ready to start trying to get some code utilizing yamlator into production when I made a terrible realization... we use centos 7 in production and all that's available is Python 3.6. Is there anything that yamlator explicitly needs in Python 3.7? Or is there a chance we can drop the version requirement down one version to 3.6+?

**Comment by ryan95f** [comment]
I believe it is down to the use of the `__future__` package which was made available in Python 3.7+. Let me see what I can do.

**Comment by wilrodriguez** [comment]
Yep, that would explain it. I see that in there now. I had been trying to figure out what exactly the requirement was, but, it definitely makes sense that it's annotations. Thanks for looking into it, and responding so quickly, I really appreciate it.

**Comment by wilrodriguez** [comment]
Looks great, thank you so much for getting to it so quickly! Though, now I have another issue, looks like dependencies are now the problem. I'm now running into a dependency conflict. Any chance you could change the dependency resolution for PyYAML to `PyYAML>=5.1` (which I'd think should be reasonably recent enough for most use-cases). It's worth noting that CentOS 7/RHEL 7 have 3.10 as their available version (as best I can tell), so an even lower version requirement might actually be desirable here for some users. In my case, we have some modules we depend on that require `5.4.1` explicitly, and while I can fix the dependencies in our internal modules, we have a few external modules with static dependencies that I can't change, though I don't see a reason why yamlator would need an explicit version of PyYAML. Conceivably if you're simply implementing the classes in your code and not using the CLI (as I'm doing) you actually wouldn't need YAML at all and could use yamlator to validate any data structure, whether pure python or coming from any other input type.

**Comment by wilrodriguez** [comment]
Good news, I was able to poke and prod at my dependencies to resolve the version conflict, so all good there. Looks like I'm all set. Though, I do still think that you might want to loosen the PyYAML version requirements in the next release. It's definitely working on 3.6 though! Thanks again Ryan!

**Comment by ryan95f** [comment]
Awesome, no problem. I will take a look at changing the dependency when I work on developing the next feature.
